use coveooss go sentry
coveooss/terraform-provider-sentry pull request #6
Opened 2022-09-19 12:20 UTC by pballandras

2022-09-19 12:21 UTC, pballandras commented on sentry/resource_sentry_issue_alert.go
> +	ctx = context.WithValue(ctx, sentry.TaskDetailRetryCountCtxKey, retryCount)
relevant part of the fix

2022-09-19 12:30 UTC, pballandras commented on .github/workflows/release.yml
> -          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
Other relevant change

2022-09-20 07:40 UTC, JHeilCoveo requested changes

2022-09-20 07:40 UTC, JHeilCoveo commented on sentry/resource_sentry_issue_alert.go
> +	ctx = context.WithValue(ctx, sentry.TaskDetailRetryCountCtxKey, retryCount)
The os.Getenv in a terraform provider is really meh...

I would much better prefer either :
* If this poll interval and retry count are very specific to `resourceSentryIssueAlertCreate` add them to the schema of this resource.
* If it could be used somewhere else add them to the configuration of this provider and set them in `sentry.Client`.

2022-09-21 08:39 UTC, jonapich reviewed
Ce serait effectivement un peu ardu d'avoir à ajouter des var d'envs dans ces affaires là.

S'il fait partie de la configuration du provider, on peut baker une valeur par défaut dans tgf mettons? Question qu'on puisse fixer ceci pour tout le monde à un endroit?

2022-09-21 12:29 UTC, JHeilCoveo commented
> Ce serait effectivement un peu ardu d'avoir à ajouter des var d'envs dans ces affaires là.
> 
> S'il fait partie de la configuration du provider, on peut baker une valeur par défaut dans tgf mettons? Question qu'on puisse fixer ceci pour tout le monde à un endroit?

Ça dépend si le provider est généré par tgf ou ce sont les développeurs qui le précise.

2022-09-26 19:09 UTC, pballandras commented
Yeah, I'm sorry I forgot about this PR @JHeilCoveo and @jonapich, this was supposed to be a fast patch with another, more elegant schema/provider based configuration. Same with the one in go-sentry repo, I'll close both now

2022-09-26 19:09 UTC, closed without merging